- name: Configuration des serveurs
  hosts: all
  become: true
  roles:
    - { role: web, when: "'web' in group_names" }
    - { role: db, when: "'db' in group_names" }
    - { role: monitoring, when: "'monitoring' in group_names" }