name: Deploy Infra + App

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
      ARM_CLIENT_SECRET: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
      ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
      ARM_TENANT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3

      - name: 🧰 Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: 🔧 Init Terraform
        run: terraform -chdir=terraform init

      - name: 📆 Plan
        run: terraform -chdir=terraform plan -var "ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"

      - name: 🚀 Apply
        run: terraform -chdir=terraform apply -auto-approve -var "ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"

      - name: 📤 Get public IP
        id: tf_output
        run: |
          IP=$(terraform -chdir=terraform output -raw public_ip)
          echo "VM_IP=$IP" >> $GITHUB_ENV
          
      - name: 📦 Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: 🔑 Setup SSH with passphrase
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass

          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          ssh-keyscan -H "$VM_IP" >> ~/.ssh/known_hosts

          # Lance ssh-agent
          eval "$(ssh-agent -s)"

          # Ajoute la clé via un fichier temporaire déverrouillé
          sshpass -p "${{ secrets.SSH_KEY_PASSPHRASE }}" ssh-add ~/.ssh/id_rsa
        env:
          VM_IP: ${{ env.VM_IP }}


      - name: 🧺 Run Ansible playbook
        run: |
          echo "[web]" > inventory.ini
          echo "$VM_IP ansible_user=azureuser ansible_ssh_private_key_file=~/.ssh/id_rsa" >> inventory.ini
          ansible-playbook -i inventory.ini Ansible/playbook.yml
