name: Deploy Infra + App

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
      ARM_CLIENT_SECRET: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
      ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
      ARM_TENANT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3

      - name: 🧰 Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: 🔧 Init Terraform
        run: terraform -chdir=terraform init

      - name: Setup SSH public key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 644 ~/.ssh/id_rsa.pub

      - name: 📆 Plan
        run: terraform -chdir=terraform plan -var "ssh_public_key=~/.ssh/id_rsa.pub"

      - name: 🚀 Apply
        run: terraform -chdir=terraform apply -auto-approve -var "ssh_public_key=~/.ssh/id_rsa.pub"
          
      - name: 📦 Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: 🔑 Setup SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa_devops
          chmod 600 ~/.ssh/id_rsa_devops
          ssh-keyscan -H "$(terraform -chdir=terraform output -raw bastion_public_ip)" >> ~/.ssh/known_hosts

      - name: 🧺 Run Ansible playbook
        run: |
          chmod +x ./run_ansible.sh
          chmod +x ./generate_inventories.sh
          ./run_ansible.sh
